FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache build-base git

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux 

COPY ./backend/go.mod ./backend/go.sum ./backend/

WORKDIR /app/backend
RUN go mod download

COPY ./backend .

RUN go build -trimpath -ldflags="-s -w" -o console ./cmd/console/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/backend/console /app/console

ENTRYPOINT ["/app/console"]