# 1. Node.js tabanlı bir image kullanarak uygulamayı build ediyoruz
FROM node:16 AS build

WORKDIR /app

COPY ./frontend/package*.json ./frontend/

WORKDIR /app/frontend
RUN npm install

COPY ./frontend .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/frontend/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]