# Build Stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux 

COPY ./backend/go.mod ./backend/go.sum ./backend/

WORKDIR /app/backend
RUN go mod download
    
COPY ./backend .

RUN go build -trimpath -ldflags="-s -w" -o task ./cmd/task/main.go

FROM scratch

WORKDIR /app

COPY --from=builder /app/backend/task /app/task

ENTRYPOINT ["/app/task"]
