package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/mehmetali10/task-planner/internal/pkg/config"
	postgres_repository "github.com/mehmetali10/task-planner/internal/pkg/repository/postgres"
	"github.com/mehmetali10/task-planner/internal/task/handler"
	"github.com/mehmetali10/task-planner/internal/task/server"
	"github.com/mehmetali10/task-planner/internal/task/service"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/mehmetali10/task-planner/internal/task/docs"
)

// @title Task Planner API
// @version 1.0
// @description Task Planner API provides endpoints for managing tasks with CRUD operations.
// @termsOfService https://swagger.io/terms/
// @contact.name Mehmet Ali Mergen
// @contact.email support@taskplanner.com
// @license.name Apache 2.0
// @license.url https://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
func main() {
	if err := config.LoadConfig(); err != nil {
		log.Fatal(err)
	}

	repo := postgres_repository.NewPostgresRepo()
	service := service.NewService(repo)
	handler := handler.NewHandler(service)

	httpServer := server.NewServer(handler)
	httpServer.Start(config.GetApp().HTTPAddr)

	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)

	<-sigChan
	log.Println("Received shutdown signal, stopping server...")

	httpServer.Stop()

	log.Println("Servers stopped")
}
