# Build Stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache build-base git

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux 

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -trimpath -ldflags="-s -w" -o console ./cmd/console/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/console /app/console

ENTRYPOINT ["/app/console"]
