version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: task
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "task", "-h", "localhost"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  task:
    image: task:0.0.1
    container_name: my_task
    environment:
      HTTP_ADDR: ":8080"
      HANDLER_LOG_LEVEL: debug
      SERVICE_LOG_LEVEL: debug
      REPOSITORY_LOG_LEVEL: debug
      HTTP_SERVER_LOG_LEVEL: debug
      HTTP_ALLOWED_HEADERS: "*"
      HTTP_ALLOWED_ORIGINS: "*"
      HTTP_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      DB_HOST: my_postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_NAME: task
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

  console:
    image: console:0.0.1
    container_name: my_console
    restart: "no"
    stdin_open: true
    tty: true
    environment:
      DB_HOST: host.docker.internal  # Set to host's localhost for accessing host services
      DB_PORT: 5432
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
